<script setup lang="ts">
function updateTaskField(field: string, value: any) {
  if (field === "eventDateDay") eventDateDay.value = value;
  else if (field === "eventDateMonth") eventDateMonth.value = value;
  else if (field === "eventDateYear") eventDateYear.value = value;
  else emit("update:newTask", { ...props.newTask, [field]: value });
}
function onCalendarDateSelect(date: string) {
  emit("update:newTask", { ...props.newTask, eventDate: date });
  emit("calendar-date-select", date);
}
import { computed } from "vue";
import { defineProps, defineEmits } from "vue";
import CalendarView from "./CalendarView.vue";

const props = defineProps({
  newTask: {
    type: Object,
    required: true,
    default: () => ({}),
  },
  autoGeneratedName: {
    type: String,
    default: "",
  },
  filteredParentOptions: {
    type: Array,
    default: () => [],
  },
  activeGroup: {
    type: Object as () => { label: string; value: string | null } | null,
    default: null,
  },
});

const emit = defineEmits([
  "add-task",
  "calendar-date-select",
  "filter-parent-tasks",
  "update:newTask",
]);

import { ref, nextTick } from "vue";
// Input refs
const dayInput = ref<any>(null);
const monthInput = ref<any>(null);
const yearInput = ref<any>(null);
const hourInput = ref<any>(null);
const minuteInput = ref<any>(null);
// Auto-increment year checkbox state
const autoIncrementYear = ref(false);

// Helper: format date as yyyy-MM-dd
function formatDate(y: number, m: number, d: number) {
  return `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
}

// Update handlers with auto-advance and auto-increment logic

function updateEventDateDay(val: number | string | null) {
  if (val === null || val === "") return;
  eventDateDay.value = Number(val);
  // Auto-advance to month if 2 digits
  if (String(val).length >= 2) {
    nextTick(() => monthInput.value?.$el?.querySelector("input")?.focus());
  }
}

function updateEventDateMonth(val: number | string | null) {
  if (val === null || val === "") return;
  const month = Number(val);
  let year = eventDateYear.value;
  // Auto-increment year if enabled and month < current month
  if (autoIncrementYear.value) {
    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();
    if (month < currentMonth && year <= currentYear) {
      year = currentYear + 1;
      eventDateYear.value = year;
    }
  }
  eventDateMonth.value = month;
  // Auto-advance to hour if 2 digits
  if (String(val).length >= 2) {
    nextTick(() => hourInput.value?.$el?.querySelector("input")?.focus());
  }
}

function updateEventDateYear(val: number | string | null) {
  if (val === null || val === "") return;
  eventDateYear.value = Number(val);
}

function updateEventTimeHour(val: number | string | null) {
  if (val === null || val === "") return;
  updateTaskField("eventTimeHour", val);
  if (String(val).length >= 2) {
    nextTick(() => minuteInput.value?.$el?.querySelector("input")?.focus());
  }
}

function updateEventTimeMinute(val: number | string | null) {
  if (val === null || val === "") return;
  updateTaskField("eventTimeMinute", val);
}

// Returns a human-readable difference between the given date and today
const getTimeDifferenceDisplay = (dayDate: string) => {
  if (!dayDate) return "Select a date";

  const date = new Date(dayDate);
  const todayDate = new Date();

  // Normalize both dates to midnight for accurate day comparison
  const dateNormalized = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const todayNormalized = new Date(
    todayDate.getFullYear(),
    todayDate.getMonth(),
    todayDate.getDate()
  );

  const daysDiff = Math.floor(
    (dateNormalized.getTime() - todayNormalized.getTime()) / (1000 * 60 * 60 * 24)
  );

  if (daysDiff === 0) return "TODAY";
  if (daysDiff === 1) return "TOMORROW";
  if (daysDiff === -1) return "YESTERDAY";

  if (daysDiff > 0) {
    // Future date
    const weeksDiff = Math.floor(daysDiff / 7);

    if (weeksDiff >= 1) {
      const remainingDays = daysDiff % 7;
      if (remainingDays > 0) {
        const weekText = weeksDiff === 1 ? "week" : "weeks";
        const dayText = remainingDays === 1 ? "day" : "days";
        return `In ${weeksDiff} ${weekText} ${remainingDays} ${dayText}`;
      }
      const weekText = weeksDiff === 1 ? "week" : "weeks";
      return `In ${weeksDiff} ${weekText}`;
    }

    const dayText = daysDiff === 1 ? "day" : "days";
    return `In ${daysDiff} ${dayText}`;
  } else {
    // Past date
    const absDaysDiff = Math.abs(daysDiff);
    const weeksDiff = Math.floor(absDaysDiff / 7);

    if (weeksDiff >= 1) {
      const remainingDays = absDaysDiff % 7;
      if (remainingDays > 0) {
        const weekText = weeksDiff === 1 ? "week" : "weeks";
        const dayText = remainingDays === 1 ? "day" : "days";
        return `${weeksDiff} ${weekText} ${remainingDays} ${dayText} ago`;
      }
      const weekText = weeksDiff === 1 ? "week" : "weeks";
      return `${weeksDiff} ${weekText} ago`;
    }

    const dayText = absDaysDiff === 1 ? "day" : "days";
    return `${absDaysDiff} ${dayText} ago`;
  }
};
// Computed for eventDate parts, always in sync with eventDate
const eventDate = computed(() => props.newTask.eventDate || "");
const eventDateParts = computed(() => eventDate.value.split("-"));
const eventDateYear = computed({
  get: () =>
    eventDateParts.value[0] ? Number(eventDateParts.value[0]) : new Date().getFullYear(),
  set: (val: number) => {
    if (eventDateParts.value.length === 3) {
      emit("update:newTask", {
        ...props.newTask,
        eventDate: `${val}-${eventDateParts.value[1]}-${eventDateParts.value[2]}`,
      });
    }
  },
});
const eventDateMonth = computed({
  get: () =>
    eventDateParts.value[1] ? Number(eventDateParts.value[1]) : new Date().getMonth() + 1,
  set: (val: number) => {
    if (eventDateParts.value.length === 3) {
      emit("update:newTask", {
        ...props.newTask,
        eventDate: `${eventDateParts.value[0]}-${String(val).padStart(2, "0")}-${
          eventDateParts.value[2]
        }`,
      });
    }
  },
});
const eventDateDay = computed({
  get: () =>
    eventDateParts.value[2] ? Number(eventDateParts.value[2]) : new Date().getDate(),
  set: (val: number) => {
    if (eventDateParts.value.length === 3) {
      emit("update:newTask", {
        ...props.newTask,
        eventDate: `${eventDateParts.value[0]}-${eventDateParts.value[1]}-${String(
          val
        ).padStart(2, "0")}`,
      });
    }
  },
});
const priorityOptions = [
  {
    label: "Lo",
    value: "low",
    icon: "low_priority",
    color: "cyan-3",
    textColor: "grey-9",
  },
  {
    label: "Med",
    value: "medium",
    icon: "drag_handle",
    color: "brown-7",
    textColor: "white",
  },
  {
    label: "Hi",
    value: "high",
    icon: "priority_high",
    color: "orange",
    textColor: "white",
  },
  {
    label: "Crit",
    value: "critical",
    icon: "warning",
    color: "negative",
    textColor: "white",
  },
];

function onSubmit(event: Event) {
  event.preventDefault();
  emit("add-task");
}
</script>

<template>
  <q-card class="q-mb-md">
    <q-card-section>
      <q-form @submit="onSubmit" class="q-gutter-md">
        <div v-if="newTask.type_id === 'TimeEvent'">
          <CalendarView
            :selected-date="newTask.eventDate"
            @update:selected-date="onCalendarDateSelect"
          />
          <div class="text-h6 row items-center q-gutter-sm q-mb-md">
            <q-icon name="add_circle" color="positive" size="md" />
            <span>Add new thing</span>
          </div>
          <div class="row q-gutter-sm q-mb-md">
            <q-card flat bordered class="q-pa-sm">
              <div class="text-caption text-grey-7 q-mb-xs">Date</div>
              <div class="row q-gutter-xs">
                <q-input
                  ref="dayInput"
                  :model-value="eventDateDay"
                  @update:model-value="updateEventDateDay"
                  @focus="(e) => (e.target as HTMLInputElement)?.select && (e.target as HTMLInputElement).select()"
                  type="number"
                  label="Day"
                  outlined
                  dense
                  min="1"
                  max="31"
                  style="max-width: 80px"
                />
                <q-input
                  ref="monthInput"
                  :model-value="eventDateMonth"
                  @update:model-value="updateEventDateMonth"
                  @focus="(e) => (e.target as HTMLInputElement)?.select && (e.target as HTMLInputElement).select()"
                  type="number"
                  label="Month"
                  outlined
                  dense
                  min="1"
                  max="12"
                  style="max-width: 80px"
                />
              </div>
            </q-card>
            <q-card flat bordered class="q-pa-sm">
              <div class="row q-gutter-xs">
                <q-input
                  ref="hourInput"
                  :model-value="newTask.eventTimeHour"
                  @update:model-value="updateEventTimeHour"
                  type="number"
                  label="Hour"
                  outlined
                  dense
                  min="0"
                  max="23"
                  style="max-width: 80px"
                />
                <q-input
                  ref="minuteInput"
                  :model-value="newTask.eventTimeMinute"
                  @update:model-value="updateEventTimeMinute"
                  type="number"
                  label="Minute"
                  outlined
                  dense
                  min="0"
                  max="59"
                  style="max-width: 80px"
                />
              </div>
            </q-card>
            <q-card flat bordered class="q-pa-sm">
              <div class="row items-center justify-between q-mb-xs">
                <div class="text-caption text-grey-7">Year</div>
                <q-checkbox v-model="autoIncrementYear" dense size="xs" label="Auto" />
              </div>
              <q-input
                ref="yearInput"
                :model-value="eventDateYear"
                @update:model-value="updateEventDateYear"
                type="number"
                label="Year"
                outlined
                dense
                style="max-width: 100px"
              />
            </q-card>
            <q-card flat bordered class="q-pa-sm">
              <div class="text-caption text-grey-7 q-mb-xs">Time Difference</div>
              <div class="text-h6 text-primary text-weight-bold">
                {{ getTimeDifferenceDisplay(newTask.eventDate) }}
              </div>
            </q-card>
            <q-card flat bordered class="q-pa-sm">
              <div class="text-caption text-grey-7 q-mb-xs">Priority</div>
              <div class="column q-gutter-xs">
                <div class="row q-gutter-xs">
                  <q-btn
                    v-for="option in priorityOptions.slice(0, 2)"
                    :key="option.value"
                    :color="newTask.priority === option.value ? option.color : 'grey-3'"
                    :text-color="
                      newTask.priority === option.value ? option.textColor : 'grey-7'
                    "
                    :icon="option.icon"
                    :label="option.label"
                    size="sm"
                    @click="updateTaskField('priority', option.value)"
                    :unelevated="newTask.priority === option.value"
                    :outline="newTask.priority !== option.value"
                  />
                </div>
                <div class="row q-gutter-xs">
                  <q-btn
                    v-for="option in priorityOptions.slice(2, 4)"
                    :key="option.value"
                    :color="newTask.priority === option.value ? option.color : 'grey-3'"
                    :text-color="
                      newTask.priority === option.value ? option.textColor : 'grey-7'
                    "
                    :icon="option.icon"
                    :label="option.label"
                    size="sm"
                    @click="updateTaskField('priority', option.value)"
                    :unelevated="newTask.priority === option.value"
                    :outline="newTask.priority !== option.value"
                  />
                </div>
              </div>
            </q-card>
          </div>
        </div>
        <div class="row" style="gap: 12px">
          <div class="col column" style="gap: 12px">
            <q-input
              :model-value="autoGeneratedName"
              label="Automatic name from description"
              outlined
              readonly
              bg-color="grey-2"
            />
            <q-input
              :model-value="newTask.name"
              label="Own task name"
              outlined
              @update:model-value="
                (val) => {
                  if (val && typeof val === 'string')
                    updateTaskField('name', val.charAt(0).toUpperCase() + val.slice(1));
                }
              "
            />
          </div>
          <q-input
            :model-value="newTask.description"
            label="Description"
            outlined
            type="textarea"
            rows="4"
            class="col"
            @update:model-value="(val) => updateTaskField('description', val)"
          />
        </div>
        <div class="row" style="gap: 12px">
          <q-select
            :model-value="newTask.parent_id"
            :options="filteredParentOptions"
            label="Parent Task (optional)"
            outlined
            clearable
            use-input
            input-debounce="0"
            @filter="$emit('filter-parent-tasks', $event)"
            @update:model-value="(val) => updateTaskField('parent_id', val)"
            option-value="value"
            option-label="label"
            emit-value
            map-options
            class="col"
          >
            <template v-slot:option="scope">
              <q-item v-bind="scope.itemProps">
                <q-item-section avatar>
                  <q-icon :name="scope.opt.icon" />
                </q-item-section>
                <q-item-section>
                  <q-item-label>{{ scope.opt.label }}</q-item-label>
                </q-item-section>
              </q-item>
            </template>
            <template v-slot:selected-item="scope">
              <q-chip
                removable
                @remove="updateTaskField('parent_id', null)"
                color="primary"
                text-color="white"
                :icon="scope.opt.icon"
              >
                {{ scope.opt.label }}
              </q-chip>
            </template>
          </q-select>
        </div>
        <div class="row items-center justify-center">
          <q-btn type="submit" color="primary" label="Add Task" />
          <div
            v-if="activeGroup && activeGroup.value"
            class="text-caption text-grey-7 q-ml-md"
          >
            <q-icon name="info" size="xs" class="q-mr-xs" />
            Task will be added to:
            <strong>{{ activeGroup.label.split(" (")[0] }}</strong>
          </div>
          <div v-else class="text-caption text-warning q-ml-md">
            <q-icon name="warning" size="xs" class="q-mr-xs" />
            Please select an active group (not "All Groups")
          </div>
        </div>
      </q-form>
    </q-card-section>
  </q-card>
</template>
