<template>
  <q-card class="q-mb-md">
    <q-card-section>
      <q-form @submit="onSubmit" class="q-gutter-md">
        <div v-if="newTask.type_id === 'TimeEvent'">
          <CalendarView
            :selected-date="newTask.eventDate"
            @update:selected-date="$emit('calendar-date-select', $event)"
          />
          <div class="text-h6 row items-center q-gutter-sm q-mb-md">
            <q-icon name="add_circle" color="positive" size="md" />
            <span>Add new thing</span>
          </div>
          <div class="row q-gutter-sm q-mb-md">
            <!-- Date, Hour, Year, Time Difference Panels (copy from original) -->
            <slot name="date-inputs" />
          </div>
        </div>
        <div class="row" style="gap: 12px">
          <div class="col column" style="gap: 12px">
            <q-input
              :model-value="autoGeneratedName"
              label="Automatic name from description"
              outlined
              readonly
              bg-color="grey-2"
            />
            <q-input
              :model-value="newTask.name"
              label="Own task name"
              outlined
              @update:model-value="(val) => { if (val && typeof val === 'string') updateTaskField('name', val.charAt(0).toUpperCase() + val.slice(1)); }"
            />
          </div>
          <q-input
            :model-value="newTask.description"
            label="Description"
            outlined
            type="textarea"
            rows="4"
            class="col"
            @update:model-value="val => updateTaskField('description', val)"
          />
        </div>
        <div class="row" style="gap: 12px">
          <q-select
            :model-value="newTask.parent_id"
            :options="filteredParentOptions"
            label="Parent Task (optional)"
            outlined
            clearable
            use-input
            input-debounce="0"
            @filter="$emit('filter-parent-tasks', $event)"
            @update:model-value="val => updateTaskField('parent_id', val)"
            option-value="value"
            option-label="label"
            emit-value
            map-options
            class="col"
          >
            <template v-slot:option="scope">
              <q-item v-bind="scope.itemProps">
                <q-item-section avatar>
                  <q-icon :name="scope.opt.icon" />
                </q-item-section>
                <q-item-section>
                  <q-item-label>{{ scope.opt.label }}</q-item-label>
                </q-item-section>
              </q-item>
            </template>
            <template v-slot:selected-item="scope">
              <q-chip
                removable
                @remove="updateTaskField('parent_id', null)"
                color="primary"
                text-color="white"
                :icon="scope.opt.icon"
              >
                {{ scope.opt.label }}
              </q-chip>
            </template>
          </q-select>
        </div>
        <div class="row items-center justify-center">
          <q-btn type="submit" color="primary" label="Add Task" />
          <div
            v-if="activeGroup && activeGroup.value"
            class="text-caption text-grey-7 q-ml-md"
          >
            <q-icon name="info" size="xs" class="q-mr-xs" />
            Task will be added to:
            <strong>{{ activeGroup.label.split(" (")[0] }}</strong>
          </div>
          <div v-else class="text-caption text-warning q-ml-md">
            <q-icon name="warning" size="xs" class="q-mr-xs" />
            Please select an active group (not "All Groups")
          </div>
        </div>
      </q-form>
    </q-card-section>
  </q-card>
</template>

<script setup lang="ts">
import { defineProps, defineEmits } from 'vue';
import CalendarView from "./CalendarView.vue";

const props = defineProps({
  newTask: {
    type: Object,
    required: true,
    default: () => ({})
  },
  autoGeneratedName: {
    type: String,
    default: ''
  },
  filteredParentOptions: {
    type: Array,
    default: () => []
  },
  activeGroup: {
    type: Object as () => { label: string; value: string | null } | null,
    default: null
  },
});

const emit = defineEmits([
  'add-task',
  'calendar-date-select',
  'filter-parent-tasks',
  'update:newTask',
]);

function onSubmit(event: Event) {
  event.preventDefault();
  emit('add-task');
}

function updateTaskField(field: string, value: any) {
  emit('update:newTask', { ...props.newTask, [field]: value });
}
</script>
