const today = new Date().toISOString().slice(0, 10);
const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

const days: Record<string, any> = {};

days[today] = {
  date: today,
  tasks: [
    {
      id: 't-1',
      name: 'Milk',
      description: '2L skimmed',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-28',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-4',
      name: 'Chocolate',
      description: 'Dark 70% 100g',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-0',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-5',
      name: 'Bananas',
      description: '6 pcs',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-8',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-6',
      name: 'Apples',
      description: '1 kg',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-1',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-7',
      name: 'Carrot',
      description: '1 kg',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-14',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-8',
      name: 'Radish',
      description: 'Bunch',
      date: today,
      priority: 'medium',
      status_id: 1,
      type_id: 'Replenish',
      color_set: 'set-4',
      groupId: 'g-house',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 't-2',
      name: 'Meeting with team',
      description: 'Discuss roadmap',
      date: today,
      eventTime: '14:00',
      priority: 'high',
      status_id: 1,
      type_id: 'TimeEvent',
      groupId: 'g-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  notes: '',
};

days[tomorrow] = {
  date: tomorrow,
  tasks: [
    {
      id: 't-3',
      name: 'Prepare slides',
      description: 'Slides for presentation',
      date: tomorrow,
      priority: 'low',
      status_id: 1,
      type_id: 'Todo',
      groupId: 'g-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  notes: '',
};

export const sampleData = {
  groups: [
    { id: 'g-family', name: 'Family', color: '#1976d2', icon: 'group' },
    { id: 'g-house', name: 'House', parentId: 'g-family', color: '#c9a676', icon: 'home' },
    { id: 'g-adam', name: 'Adam', parentId: 'g-family', color: '#4caf50', icon: 'person' },
    { id: 'g-nataly', name: 'Nataly', parentId: 'g-family', color: '#ffb300', icon: 'person' },
    { id: 'g-richard', name: 'Richard', parentId: 'g-family', color: '#90caf9', icon: 'person' },
    { id: 'g-elisa', name: 'Elisa', parentId: 'g-family', color: '#ce93d8', icon: 'person' },
    { id: 'g-car1', name: 'Car 1', parentId: 'g-family', color: '#9e9e9e', icon: 'directions_car' },
    // Adam's subgroups
    { id: 'g-adam-work', name: 'Work', parentId: 'g-adam', color: '#1976d2', icon: 'work' },
    {
      id: 'g-adam-singing',
      name: 'Singing',
      parentId: 'g-adam',
      color: '#ab47bc',
      icon: 'music_note',
    },
    {
      id: 'g-adam-sport',
      name: 'Sport',
      parentId: 'g-adam',
      color: '#ff5252',
      icon: 'sports_soccer',
    },
  ],
  days,
};
